all:
	gcc -Wall -fPIC -O3 -c  ffile.c -o ../build/ffile.o -DBITS_PER_LONG=64
	# gcc -Wall -fPIC -shared -o ffile.so ffile.o -ldl
	# gcc -Wall -fPIC -shared -g -o ../ffile.so fileops.c genops.c ffile.c